[package]
name = "bodhi_config"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
serde = { workspace = true }
toml = { workspace = true }
bodhi_result = { path = "../bodhi_result" }
bodhi_error = { path = "../bodhi_error" }
