[package]
name = "bodhi_error"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
thiserror = { workspace = true }
toml = { workspace = true }
clap = { workspace = true }
